theme: jekyll-theme-minimal
title: 🎬 C1n3mada presents: Money, Money, Movies – The secrets of movies’ box office success 🎥
description: Title page of the datastory
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
