#theme: jekyll-theme-minimal
theme: minimal-mistakes-jekyll
title: C1n3mada datastory
description: Website to present the datastory of a project
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Introduction
    url: /introduction
  - title: Echo
    url: /movies/echo
  - title: Tongues
    url: /movies/tongues
