theme: jekyll-theme-minimal
title: C1n3mada datastory
description: Title page of the datastory
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Introduction
    url: introduction
