theme: jekyll-theme-minimal
title: C1n3mada datastory
description: Website to present the datastory of a project
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Introduction
    url: introduction
